<?php header('Content-Type: application/json; charset=utf-8');
?>
<!--
<html>
    <head>
    	
		<meta http-equiv="Content-Language" content="de" />
        <meta http-equiv="Content-Style-Type" content="text/css"/>
        <meta http-equiv="Content-Script-Type" content="text/javascript"/>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	
    </head>
    <body>
<?= $this->layout()->content ?>
</body>
</html>


-->